### ISSUE TITLE
How configure the "custom fileds" for Begin and End time?

### ISSUE THREAD

**Issue by tuxflo** [fathomssen/redtimer#97]
I installed the redmine_shared_api plugin on my redmine server but I'm unable to select values from the Dropdown bar below the checkbox for "Custom fields".
The Dropdownbar entries are marked with "No time entry fields found".

**Comment by fathomssen** [comment]
Hi @tuxflo 

Have you configured new custom fields for time entries in the Redmine admin panel?

I should probably update the manual...

Best regards
Frederick Thomssen

**Comment by tuxflo** [comment]
Like that?
![screenshot](https://cloud.githubusercontent.com/assets/2816893/22368185/8df63436-e485-11e6-9b24-4b0b731b3cd9.PNG)

**Comment by fathomssen** [comment]
Yep, like that. Have you tried restarting RedTimer after creating those fields? I am not sure whether the settings dialog always refreshes external values.

**Comment by tuxflo** [comment]
Ok restarted Redtimer, now I'm able to select the values in the settings menu. Time entries are saved like that:

![screenshot2](https://cloud.githubusercontent.com/assets/2816893/22368437/cb2e79c0-e486-11e6-8b97-512684e248e4.PNG)

Whats the use case for External ID field?
Is the checkbox "Text formatting" required?

Thanks a lot for the super fast reply and support, you're doing an awesome job!

**Comment by fathomssen** [comment]
Oh, I should reload those fields more often... probably every time that the URL and API key have been changed or the Apply button has been pressed.

The External ID field is used by the command line interface (CLI). When you create a new issue using the CLI, you probably want to provide a unique ID to the issue (like the issue ID - but you cannot explicitly set the issue ID). If an issue with the specified unique ID (i.e. the External ID) already exists, the command line interface can update the issue instead of creating a new one.

No, the "Text formatting" is not required.

My pleasure! I will most hopefully update the manual soon. First, I would like to update to RedTimer 1.2.1 though :)

Best regards
Frederick Thomssen

**Comment by tuxflo** [comment]
Thanks again for the reply and keep up the great work!
